# Data Based Problems

The DESDEO framework provides handling of data-driven optimization problems. Some methods, such as E-NAUTILUS in `desdeo-mcdm`, find the most preffered solution from a provided dataset. Other methods, such as most of the EA's from `desdeo-emo`, require a surrogate model to be trained for each of the objectives. The `desdeo_problem` provides support for both of these cases. 

For data based problems, use the data specific objective/problem classes

In [1]:
import pandas as pd
import numpy as np

VectorDataObjective is an objective class that can handle data, as well as multi-objective evaluators.

The GaussianProcessRegressor here is same as the one in scikit-learn with one small difference. The predict method has been replaced to return uncertainity values (in the form of standard deviation of the prediction) by default. It supports hyperparameters in the same format as the sklearn method.

In [2]:
from desdeo_problem.Objective import VectorDataObjective as VDO
from desdeo_problem.surrogatemodels.SurrogateModels import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern

### Creating some random data

'a' and 'b' are randomly generated between 0 and 1.

f1 = a + b  
f2 = a * b

For data-driven problems, make sure that the input dataset is in the pandas DataFrame format, with the column names being the same as the variable/objective names.

In [3]:
data = np.random.rand(100,2)

f1 = (data[:,0]+data[:,1]).reshape(-1,1)
f2 = (data[:,0]*data[:,1]).reshape(-1,1)

data = np.hstack((data, f1, f2))

X = ['a','b']
y = ['f1','f2']
datapd = pd.DataFrame(data, columns=X+y)
datapd.head()

a         b        f1        f2
0  0.186979  0.443815  0.630795  0.082984
1  0.623897  0.508347  1.132244  0.317156
2  0.339249  0.842154  1.181403  0.285700
3  0.381914  0.860903  1.242817  0.328791
4  0.888904  0.340132  1.229036  0.302345

### Using VectorDataObjective class

The `VectorDataObjective` class takes as its input the data in a dataframe format and the objective names in a list.

In [4]:
obj = VDO(data=datapd, name=y)

### Training surrogate models

Pass the surrogate modelling technique and the model parameters to the train method of the objective instance.

If only one modelling technique is passed, the `model_parameters` should be a dict (or None) and this will be used for all the objectives.

If multiple modelling techniques are passed, `models` should be the list of modelling techniques, and `model_parameters` should be a list of dicts. The length of these lists should be the same as the number of objectives and each list element will be used to train one objective in order.

In [5]:
obj.train(models=GaussianProcessRegressor, model_parameters={'kernel': Matern(nu=1.5)})

### Using surrogate models to evaluate objective values

Use the obj.evaluate method to get predictions. Note that `use_surrogates` should be true.

In [6]:
print(obj.evaluate(np.asarray([[0.5,0.3]]), use_surrogate=True))

Objective Evaluation Results Object 
Objective values are: 
    f1        f2
0  0.8  0.150002
Uncertainity values are: 
    f1        f2
0  0.0  0.000845



In [7]:
obj._model_trained

{'f1': True, 'f2': True}

### Creating data problem class

Creating the objective class should be bypassed for now, use `DataProblem` class directly with the data in a dataframe.

The `DataProblem` provides a `train` method which trains all the objectives sequentially. The input arguments for this train method is the same as that of the `VectorDataObjective` class.

To make sure that the `evaluate` method uses the surrogate models for evaluations, pass the `use_surrogate=True` argument.

In [8]:
from desdeo_problem.Problem import DataProblem

In [9]:
prob = DataProblem(data=datapd, objective_names=y, variable_names=X)

In [10]:
prob.train(GaussianProcessRegressor)

In [11]:
print(prob.evaluate(np.asarray([[0.1,0.8], [0.5,0.3]]), use_surrogate=True))

Evaluation Results Object 
Objective values are: 
[[0.90000222 0.07999896]
 [0.79999987 0.1499993 ]]
Constraint violation values are: 
None
Fitness values are: 
[[0.90000222 0.07999896]
 [0.79999987 0.1499993 ]]
Uncertainity values are: 
[[0.00098456 0.00098456]
 [0.004962   0.004962  ]]



## Lipschitian models

In [12]:
from desdeo_problem.surrogatemodels.lipschitzian import LipschitzianRegressor

In [13]:
prob = DataProblem(data=datapd, objective_names=y, variable_names=X)

In [14]:
prob.train(LipschitzianRegressor)

In [15]:
print(prob.evaluate(np.asarray([[0.1,0.8], [0.5,0.3]]), use_surrogate=True))

Evaluation Results Object 
Objective values are: 
[[0.9        0.09520284]
 [0.8        0.16391092]]
Constraint violation values are: 
None
Fitness values are: 
[[0.9        0.09520284]
 [0.8        0.16391092]]
Uncertainity values are: 
[[4.44089210e-16 4.10520276e-02]
 [4.44089210e-16 5.17472194e-02]]

